language: cpp
sudo: false
matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
addons:
  apt:
    packages:
      - cmake
before_install:
    - eval "${MATRIX_EVAL}"
before_script:
  - cmake --version
  - mkdir build
  - cd build
  - cmake . ${TRAVIS_BUILD_DIR}
  - make clean
  - make
script: echo ok
