
trigger:
- master

jobs:
- job: Windows
  pool:
    vmImage: 'windows-latest'
    name: Hosted VS2017

  steps:
  - script: |
     mkdir build & cd build
     cmake -A x64 ..
     call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
     cmake --build . -- /p:Configuration=Release
  displayName: 'build QPanda on Windows vm'
